// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: request_probe.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestProbe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HttpRequest   string                 `protobuf:"bytes,1,opt,name=http_request,json=httpRequest,proto3" json:"http_request,omitempty"`
	NullProbe     []*Match               `protobuf:"bytes,2,rep,name=null_probe,json=nullProbe,proto3" json:"null_probe,omitempty"`
	Rarity_1      []*Match               `protobuf:"bytes,3,rep,name=rarity_1,json=rarity1,proto3" json:"rarity_1,omitempty"`
	Rarity_2      []*Match               `protobuf:"bytes,4,rep,name=rarity_2,json=rarity2,proto3" json:"rarity_2,omitempty"`
	Rarity_3      []*Match               `protobuf:"bytes,5,rep,name=rarity_3,json=rarity3,proto3" json:"rarity_3,omitempty"`
	Rarity_4      []*Match               `protobuf:"bytes,6,rep,name=rarity_4,json=rarity4,proto3" json:"rarity_4,omitempty"`
	Rarity_5      []*Match               `protobuf:"bytes,7,rep,name=rarity_5,json=rarity5,proto3" json:"rarity_5,omitempty"`
	Rarity_6      []*Match               `protobuf:"bytes,8,rep,name=rarity_6,json=rarity6,proto3" json:"rarity_6,omitempty"`
	Rarity_7      []*Match               `protobuf:"bytes,9,rep,name=rarity_7,json=rarity7,proto3" json:"rarity_7,omitempty"`
	Rarity_8      []*Match               `protobuf:"bytes,10,rep,name=rarity_8,json=rarity8,proto3" json:"rarity_8,omitempty"`
	Rarity_9      []*Match               `protobuf:"bytes,11,rep,name=rarity_9,json=rarity9,proto3" json:"rarity_9,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestProbe) Reset() {
	*x = RequestProbe{}
	mi := &file_request_probe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestProbe) ProtoMessage() {}

func (x *RequestProbe) ProtoReflect() protoreflect.Message {
	mi := &file_request_probe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestProbe.ProtoReflect.Descriptor instead.
func (*RequestProbe) Descriptor() ([]byte, []int) {
	return file_request_probe_proto_rawDescGZIP(), []int{0}
}

func (x *RequestProbe) GetHttpRequest() string {
	if x != nil {
		return x.HttpRequest
	}
	return ""
}

func (x *RequestProbe) GetNullProbe() []*Match {
	if x != nil {
		return x.NullProbe
	}
	return nil
}

func (x *RequestProbe) GetRarity_1() []*Match {
	if x != nil {
		return x.Rarity_1
	}
	return nil
}

func (x *RequestProbe) GetRarity_2() []*Match {
	if x != nil {
		return x.Rarity_2
	}
	return nil
}

func (x *RequestProbe) GetRarity_3() []*Match {
	if x != nil {
		return x.Rarity_3
	}
	return nil
}

func (x *RequestProbe) GetRarity_4() []*Match {
	if x != nil {
		return x.Rarity_4
	}
	return nil
}

func (x *RequestProbe) GetRarity_5() []*Match {
	if x != nil {
		return x.Rarity_5
	}
	return nil
}

func (x *RequestProbe) GetRarity_6() []*Match {
	if x != nil {
		return x.Rarity_6
	}
	return nil
}

func (x *RequestProbe) GetRarity_7() []*Match {
	if x != nil {
		return x.Rarity_7
	}
	return nil
}

func (x *RequestProbe) GetRarity_8() []*Match {
	if x != nil {
		return x.Rarity_8
	}
	return nil
}

func (x *RequestProbe) GetRarity_9() []*Match {
	if x != nil {
		return x.Rarity_9
	}
	return nil
}

type Match struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProbeName      string                 `protobuf:"bytes,1,opt,name=probe_name,json=probeName,proto3" json:"probe_name,omitempty"`
	Matches        []string               `protobuf:"bytes,2,rep,name=matches,proto3" json:"matches,omitempty"`
	MatchCount     uint64                 `protobuf:"varint,3,opt,name=match_count,json=matchCount,proto3" json:"match_count,omitempty"`
	Softmatches    []string               `protobuf:"bytes,4,rep,name=softmatches,proto3" json:"softmatches,omitempty"`
	SoftmatchCount uint64                 `protobuf:"varint,5,opt,name=softmatch_count,json=softmatchCount,proto3" json:"softmatch_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_request_probe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_request_probe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_request_probe_proto_rawDescGZIP(), []int{1}
}

func (x *Match) GetProbeName() string {
	if x != nil {
		return x.ProbeName
	}
	return ""
}

func (x *Match) GetMatches() []string {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *Match) GetMatchCount() uint64 {
	if x != nil {
		return x.MatchCount
	}
	return 0
}

func (x *Match) GetSoftmatches() []string {
	if x != nil {
		return x.Softmatches
	}
	return nil
}

func (x *Match) GetSoftmatchCount() uint64 {
	if x != nil {
		return x.SoftmatchCount
	}
	return 0
}

type NmapProbeResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*RequestProbe        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NmapProbeResults) Reset() {
	*x = NmapProbeResults{}
	mi := &file_request_probe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NmapProbeResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NmapProbeResults) ProtoMessage() {}

func (x *NmapProbeResults) ProtoReflect() protoreflect.Message {
	mi := &file_request_probe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NmapProbeResults.ProtoReflect.Descriptor instead.
func (*NmapProbeResults) Descriptor() ([]byte, []int) {
	return file_request_probe_proto_rawDescGZIP(), []int{2}
}

func (x *NmapProbeResults) GetResults() []*RequestProbe {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_request_probe_proto protoreflect.FileDescriptor

const file_request_probe_proto_rawDesc = "" +
	"\n" +
	"\x13request_probe.proto\x12\x05proto\"\xcf\x03\n" +
	"\fRequestProbe\x12!\n" +
	"\fhttp_request\x18\x01 \x01(\tR\vhttpRequest\x12+\n" +
	"\n" +
	"null_probe\x18\x02 \x03(\v2\f.proto.MatchR\tnullProbe\x12'\n" +
	"\brarity_1\x18\x03 \x03(\v2\f.proto.MatchR\ararity1\x12'\n" +
	"\brarity_2\x18\x04 \x03(\v2\f.proto.MatchR\ararity2\x12'\n" +
	"\brarity_3\x18\x05 \x03(\v2\f.proto.MatchR\ararity3\x12'\n" +
	"\brarity_4\x18\x06 \x03(\v2\f.proto.MatchR\ararity4\x12'\n" +
	"\brarity_5\x18\a \x03(\v2\f.proto.MatchR\ararity5\x12'\n" +
	"\brarity_6\x18\b \x03(\v2\f.proto.MatchR\ararity6\x12'\n" +
	"\brarity_7\x18\t \x03(\v2\f.proto.MatchR\ararity7\x12'\n" +
	"\brarity_8\x18\n" +
	" \x03(\v2\f.proto.MatchR\ararity8\x12'\n" +
	"\brarity_9\x18\v \x03(\v2\f.proto.MatchR\ararity9\"\xac\x01\n" +
	"\x05Match\x12\x1d\n" +
	"\n" +
	"probe_name\x18\x01 \x01(\tR\tprobeName\x12\x18\n" +
	"\amatches\x18\x02 \x03(\tR\amatches\x12\x1f\n" +
	"\vmatch_count\x18\x03 \x01(\x04R\n" +
	"matchCount\x12 \n" +
	"\vsoftmatches\x18\x04 \x03(\tR\vsoftmatches\x12'\n" +
	"\x0fsoftmatch_count\x18\x05 \x01(\x04R\x0esoftmatchCount\"A\n" +
	"\x10NmapProbeResults\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.proto.RequestProbeR\aresultsB[\n" +
	"\tcom.protoB\x11RequestProbeProtoP\x01Z\a./proto\xa2\x02\x03PXX\xaa\x02\x05Proto\xca\x02\x05Proto\xe2\x02\x11Proto\\GPBMetadata\xea\x02\x05Protob\x06proto3"

var (
	file_request_probe_proto_rawDescOnce sync.Once
	file_request_probe_proto_rawDescData []byte
)

func file_request_probe_proto_rawDescGZIP() []byte {
	file_request_probe_proto_rawDescOnce.Do(func() {
		file_request_probe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_probe_proto_rawDesc), len(file_request_probe_proto_rawDesc)))
	})
	return file_request_probe_proto_rawDescData
}

var file_request_probe_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_request_probe_proto_goTypes = []any{
	(*RequestProbe)(nil),     // 0: proto.RequestProbe
	(*Match)(nil),            // 1: proto.Match
	(*NmapProbeResults)(nil), // 2: proto.NmapProbeResults
}
var file_request_probe_proto_depIdxs = []int32{
	1,  // 0: proto.RequestProbe.null_probe:type_name -> proto.Match
	1,  // 1: proto.RequestProbe.rarity_1:type_name -> proto.Match
	1,  // 2: proto.RequestProbe.rarity_2:type_name -> proto.Match
	1,  // 3: proto.RequestProbe.rarity_3:type_name -> proto.Match
	1,  // 4: proto.RequestProbe.rarity_4:type_name -> proto.Match
	1,  // 5: proto.RequestProbe.rarity_5:type_name -> proto.Match
	1,  // 6: proto.RequestProbe.rarity_6:type_name -> proto.Match
	1,  // 7: proto.RequestProbe.rarity_7:type_name -> proto.Match
	1,  // 8: proto.RequestProbe.rarity_8:type_name -> proto.Match
	1,  // 9: proto.RequestProbe.rarity_9:type_name -> proto.Match
	0,  // 10: proto.NmapProbeResults.results:type_name -> proto.RequestProbe
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_request_probe_proto_init() }
func file_request_probe_proto_init() {
	if File_request_probe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_probe_proto_rawDesc), len(file_request_probe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_probe_proto_goTypes,
		DependencyIndexes: file_request_probe_proto_depIdxs,
		MessageInfos:      file_request_probe_proto_msgTypes,
	}.Build()
	File_request_probe_proto = out.File
	file_request_probe_proto_goTypes = nil
	file_request_probe_proto_depIdxs = nil
}
